[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist"


[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "express",
    "dotenv",
    "pg",
    "@supabase/supabase-js",
    "jsonwebtoken",
    "express-validator",
    "@google-cloud/bigquery"
  ]

  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
